ports:
  - port: 8080
    onOpen: open-preview
tasks:
  - name: Front End
    init: cd frontend && npm install
    command: npm run serve
  - name: Airnode
    command: yarn start-airnode
  - name: Contracts
    init: cd hardhat && npm i
    command: yarn build && echo "\nTo deploy a new requester contract run:\n\nyarn deploy-requester\n"
